### ISSUE TITLE
Burndown Chart Sprint 2

### ISSUE THREAD

**Issue by cynthiac3** [Lattakia/Project341#14]
![burndown chart - s2](https://cloud.githubusercontent.com/assets/23585931/22813035/8f4d68d6-ef16-11e6-9d8c-fddba8922424.PNG)

**Comment by cynthiac3** [comment]
![burndown chart - sprint 2](https://cloud.githubusercontent.com/assets/23585931/23044295/934e50e2-f46d-11e6-9673-9a3b96c85483.PNG)
![tables for burndown chart sprint 2](https://cloud.githubusercontent.com/assets/23585931/23044296/9355da38-f46d-11e6-857a-701c38ee561d.PNG)

**Comment by Chasiwpaw** [comment]
The chart and the table is nicely done, I think we can also include a rough summary of who was involved in the tasks :)
