### ISSUE TITLE
User Story # 6

### ISSUE THREAD

**Issue by gamecoder95** [Lattakia/Project341#8]
As a user I want to be able to login to the website into my own account.

**Comment by gamecoder95** [comment]
Task 1: Design of the index, login and sign up pages.

**Comment by gamecoder95** [comment]
Task 2: Create database for users.

**Comment by gamecoder95** [comment]
Task 3: Add verification functions for username and passwords.

**Comment by compgirl123** [comment]
Task 4: Send email to confirm the creation of the new account

**Comment by cynthiac3** [comment]
Task 5: During login, verify if the username is in the database and password match.

**Comment by Lattakia** [comment]
Task 6: Display a page with the user's appointments, and surveys depending on type of account.

**Comment by Lattakia** [comment]
Task 7: Fetch user info from database to display on profile page.

**Comment by fatin123** [comment]
Task 8: Display a profile page where the user can modify his/her information.

**Comment by Chasiwpaw** [comment]
Task 9: Debugging account authentication.
- New registering users cannot use emails that has previously been used for this site.
- Registered users needs to have their user/pass verified before entering the main page.
